%% =============================================================================
% FILE: plot_summer_temperature_sensitivity_v4.m
% PURPOSE:
%   Creates the DeltaE bar graph from previously calculated summer
%   temperature-sensitivity results.
%
% CHANGES IN V4:
%   1. Only temperature offsets from -3 to +3 C are plotted.
%   2. The 0 C offset remains at the centre.
%   3. Route-change markers are removed.
%   4. Route-change classification is not used in the plot.
%   5. Scenario mean temperatures are shown below each temperature offset.
%
% INPUT:
%   Preferred workspace variables:
%       summer_temperature_sensitivity
%       summer_temperature_results_table
%
%   Fallback MAT file:
%       summer_temperature_sensitivity_results.mat
%
% IMPORTANT:
%   This script does NOT run the optimizer.
%% =============================================================================

clc;
close all;

fprintf('Executing plot script v4 from: %s\n', mfilename('fullpath'));
fprintf('Displayed x-axis offsets: -3, -2, -1, 0, +1, +2, +3 C\n');

%% -------------------------------------------------------------------------
% 1. LOAD RESULTS
% --------------------------------------------------------------------------

results_mat_file = 'summer_temperature_sensitivity_results.mat';

workspace_has_results = ...
    exist('summer_temperature_sensitivity', 'var') && ...
    exist('summer_temperature_results_table', 'var');

if ~workspace_has_results
    if ~isfile(results_mat_file)
        error([ ...
            'Sensitivity results were not found in the workspace or current ' ...
            'folder. First run summer_temperature_sensitivity_analysis.m.']);
    end

    loaded_results = load( ...
        results_mat_file, ...
        'summer_temperature_sensitivity', ...
        'summer_temperature_results_table');

    summer_temperature_sensitivity = ...
        loaded_results.summer_temperature_sensitivity;

    summer_temperature_results_table = ...
        loaded_results.summer_temperature_results_table;
end

%% -------------------------------------------------------------------------
% 2. VALIDATE REQUIRED RESULTS
% --------------------------------------------------------------------------

required_table_variables = { ...
    'TemperatureOffset_C', ...
    'FixedRouteDeltaE_kWh', ...
    'ReoptimizedDeltaE_kWh'};

for variable_idx = 1:numel(required_table_variables)

    variable_name = required_table_variables{variable_idx};

    if ~ismember( ...
            variable_name, ...
            summer_temperature_results_table.Properties.VariableNames)

        error('Required result-table variable is missing: %s', ...
            variable_name);
    end
end

required_struct_fields = { ...
    'reference_mean_temperature_C', ...
    'reference_route_text', ...
    'reference_energy_kWh'};

for field_idx = 1:numel(required_struct_fields)

    field_name = required_struct_fields{field_idx};

    if ~isfield(summer_temperature_sensitivity, field_name)
        error('Required result-structure field is missing: %s', ...
            field_name);
    end
end

%% -------------------------------------------------------------------------
% 3. SELECT AND CHECK THE -3 TO +3 OFFSET SCENARIOS
% --------------------------------------------------------------------------

all_results_table = sortrows( ...
    summer_temperature_results_table, ...
    'TemperatureOffset_C');

% Only display scenarios from -3 C to +3 C.
plot_range_mask = ...
    all_results_table.TemperatureOffset_C >= -3 & ...
    all_results_table.TemperatureOffset_C <= 3;

results_table = all_results_table(plot_range_mask, :);

expected_temperature_offset_C = (-3:1:3)';
temperature_offset_C = results_table.TemperatureOffset_C;

if height(results_table) ~= numel(expected_temperature_offset_C) || ...
        ~isequal(temperature_offset_C(:), expected_temperature_offset_C)

    error([ ...
        'The result table must contain the offsets ' ...
        '-3, -2, -1, 0, +1, +2, +3 C.']);
end

reference_mean_temperature_C = ...
    summer_temperature_sensitivity.reference_mean_temperature_C;

reference_route_text = char(string( ...
    summer_temperature_sensitivity.reference_route_text));

reference_energy_kWh = ...
    summer_temperature_sensitivity.reference_energy_kWh;

% Scenario mean temperature =
% reference summer mean temperature + applied offset.
scenario_mean_temperature_C = ...
    reference_mean_temperature_C + temperature_offset_C;

% Optional consistency check.
if ismember( ...
        'ScenarioMeanTemperature_C', ...
        results_table.Properties.VariableNames)

    stored_mean_temperature_C = ...
        results_table.ScenarioMeanTemperature_C;

    maximum_mean_difference_C = max(abs( ...
        stored_mean_temperature_C - ...
        scenario_mean_temperature_C));

    if maximum_mean_difference_C > 1e-8
        warning([ ...
            'Stored scenario mean temperatures were inconsistent with ' ...
            'reference mean + offset. Corrected values are used.']);
    end
end

fixed_route_deltaE_kWh = ...
    results_table.FixedRouteDeltaE_kWh;

reoptimized_deltaE_kWh = ...
    results_table.ReoptimizedDeltaE_kWh;

number_of_scenarios = ...
    numel(temperature_offset_C);

plot_position = ...
    (1:number_of_scenarios)';

reference_plot_idx = ...
    find(temperature_offset_C == 0, 1);

%% -------------------------------------------------------------------------
% 4. CREATE THE BAR GRAPH
% --------------------------------------------------------------------------

figure_handle = figure( ...
    'Name', 'Summer Temperature Sensitivity - DeltaE (v4)', ...
    'NumberTitle', 'off', ...
    'Position', [100, 100, 1250, 720], ...
    'Color', 'w');

axes_handle = axes(figure_handle);

bar_handle = bar( ...
    axes_handle, ...
    plot_position, ...
    [fixed_route_deltaE_kWh, reoptimized_deltaE_kWh], ...
    'grouped');

bar_handle(1).DisplayName = ...
    'Reference Route Fixed';

bar_handle(2).DisplayName = ...
    'Route Re-optimized';

hold(axes_handle, 'on');

% Horizontal zero-reference line.
yline( ...
    axes_handle, ...
    0, ...
    'k-', ...
    'LineWidth', 1.0, ...
    'HandleVisibility', 'off');

% Original summer reference case.
xline( ...
    axes_handle, ...
    reference_plot_idx, ...
    'k--', ...
    'Reference (0 C)', ...
    'LabelOrientation', 'horizontal', ...
    'LabelVerticalAlignment', 'bottom', ...
    'HandleVisibility', 'off');

grid(axes_handle, 'on');
box(axes_handle, 'on');

axes_handle.XLim = ...
    [0.35, number_of_scenarios + 0.65];

axes_handle.XTick = ...
    plot_position;

%% -------------------------------------------------------------------------
% 5. X-AXIS LABELS
% --------------------------------------------------------------------------

offset_tick_labels = arrayfun( ...
    @(offset_value) sprintf('%+d', offset_value), ...
    temperature_offset_C, ...
    'UniformOutput', false);

axes_handle.XTickLabel = ...
    offset_tick_labels;

axes_handle.XTickLabelRotation = 0;
axes_handle.FontSize = 10;

xlabel( ...
    axes_handle, ...
    'Temperature Offset from Original Summer Profile (°C)');

% Add mean scenario temperature below each offset.
drawnow;

y_limits_before_labels = ...
    ylim(axes_handle);

y_range_for_labels = ...
    diff(y_limits_before_labels);

mean_temperature_label_y = ...
    y_limits_before_labels(1) - ...
    0.075 * y_range_for_labels;

for scenario_idx = 1:number_of_scenarios

    text( ...
        axes_handle, ...
        plot_position(scenario_idx), ...
        mean_temperature_label_y, ...
        sprintf('(%.2f °C)', ...
            scenario_mean_temperature_C(scenario_idx)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontSize', 9, ...
        'Clipping', 'off');
end

% Additional space for second row of x-axis labels.
axes_position = axes_handle.Position;

axes_handle.Position = [ ...
    axes_position(1), ...
    axes_position(2) + 0.07, ...
    axes_position(3), ...
    axes_position(4) - 0.07];

ylabel( ...
    axes_handle, ...
    '\DeltaE Relative to Original Summer Case (kWh)');

title(axes_handle, { ...
    'Summer Temperature Sensitivity of Energy-Optimal EV Routing', ...
    sprintf( ...
        ['Reference case: offset 0 °C, mean temperature %.2f °C | ' ...
         'Route: %s'], ...
        reference_mean_temperature_C, ...
        reference_route_text)});

%% -------------------------------------------------------------------------
% 6. LEGEND
% --------------------------------------------------------------------------

% Only the two bar series are included.
legend( ...
    axes_handle, ...
    'Location', 'best');

%% -------------------------------------------------------------------------
% 7. ADD FIXED-ROUTE DELTA-E VALUE LABELS
% --------------------------------------------------------------------------

try
    fixed_route_x = ...
        bar_handle(1).XEndPoints(:);

catch

    number_of_bar_series = 2;

    group_width = min( ...
        0.8, ...
        number_of_bar_series / ...
        (number_of_bar_series + 1.5));

    fixed_route_x = ...
        plot_position + ...
        (1 - (number_of_bar_series + 1) / 2) * ...
        group_width / number_of_bar_series;
end

for scenario_idx = 1:number_of_scenarios

    if ~isfinite( ...
            fixed_route_deltaE_kWh(scenario_idx))
        continue;
    end

    value_y = ...
        fixed_route_deltaE_kWh(scenario_idx);

    if value_y >= 0
        vertical_alignment = 'bottom';
    else
        vertical_alignment = 'top';
    end

    text( ...
        axes_handle, ...
        fixed_route_x(scenario_idx), ...
        value_y, ...
        sprintf('%.3f', value_y), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', vertical_alignment, ...
        'FontSize', 8, ...
        'Rotation', 90);
end

hold(axes_handle, 'off');

%% -------------------------------------------------------------------------
% 8. DISPLAY REFERENCE CHECK
% --------------------------------------------------------------------------

fprintf('\n======================================================\n');
fprintf('>>> SUMMER TEMPERATURE GRAPH V4 <<<\n');
fprintf('======================================================\n');

fprintf('Reference offset           : %+d C\n', ...
    temperature_offset_C(reference_plot_idx));

fprintf('Reference mean temperature : %.4f C\n', ...
    scenario_mean_temperature_C(reference_plot_idx));

fprintf('Reference route            : %s\n', ...
    reference_route_text);

fprintf('Reference energy           : %.4f kWh\n', ...
    reference_energy_kWh);

fprintf('Number of plotted scenarios: %d\n', ...
    number_of_scenarios);

fprintf('First offset / mean        : %+d C / %.4f C\n', ...
    temperature_offset_C(1), ...
    scenario_mean_temperature_C(1));

fprintf('Last offset / mean         : %+d C / %.4f C\n', ...
    temperature_offset_C(end), ...
    scenario_mean_temperature_C(end));

%% -------------------------------------------------------------------------
% 9. EXPORT GRAPH FILES
% --------------------------------------------------------------------------

exportgraphics( ...
    figure_handle, ...
    'summer_temperature_sensitivity_deltaE_v4.png', ...
    'Resolution', 300);

savefig( ...
    figure_handle, ...
    'summer_temperature_sensitivity_deltaE_v4.fig');

fprintf('\nSaved graph files:\n');
fprintf('  summer_temperature_sensitivity_deltaE_v4.png\n');
fprintf('  summer_temperature_sensitivity_deltaE_v4.fig\n');