%% ================================================================
% FILE: seasonal_cost_energy_breakdown_ieee.m
% PURPOSE:
%   Compare Cost-Optimal energy decomposition:
%   Summer vs Winter
%   IEEE single-column PNG, 300 DPI
% ================================================================

clc;
close all;

%% ------------------------------------------------
% 1. Results
% ------------------------------------------------

% Summer - 15 July 2025
traction_summer = 126.89;   % kWh
total_summer    = 146.10;   % kWh
hvac_summer     = total_summer - traction_summer;

% Winter - 15 January 2025
traction_winter = 126.89;   % kWh
total_winter    = 169.57;   % kWh
hvac_winter     = total_winter - traction_winter;

labels = {'Summer','Winter'};

traction_vals = [traction_summer, traction_winter];
hvac_vals     = [hvac_summer, hvac_winter];
total_vals    = traction_vals + hvac_vals;

stacked_data = [traction_vals(:), hvac_vals(:)];

%% ------------------------------------------------
% 2. Percentage comparison
% ------------------------------------------------

hvac_increase_pct = ...
    100 * (hvac_winter - hvac_summer) / hvac_summer;

total_increase_pct = ...
    100 * (total_winter - total_summer) / total_summer;

summer_hvac_share = ...
    100 * hvac_summer / total_summer;

winter_hvac_share = ...
    100 * hvac_winter / total_winter;

fprintf('\n===== SEASONAL COST-OPTIMAL COMPARISON =====\n');
fprintf('Summer HVAC energy  : %.2f kWh\n', hvac_summer);
fprintf('Winter HVAC energy  : %.2f kWh\n', hvac_winter);
fprintf('HVAC increase       : %.1f %%\n', hvac_increase_pct);
fprintf('Total energy increase: %.1f %%\n', total_increase_pct);
fprintf('Summer HVAC share   : %.1f %%\n', summer_hvac_share);
fprintf('Winter HVAC share   : %.1f %%\n', winter_hvac_share);

%% ------------------------------------------------
% 3. Figure
% ------------------------------------------------

fig_w = 3.5;
fig_h = 2.65;

f = figure( ...
    'Color','w', ...
    'Units','inches', ...
    'Position',[1 1 fig_w fig_h], ...
    'PaperPositionMode','auto');

tl = tiledlayout( ...
    f,1,1, ...
    'Padding','compact', ...
    'TileSpacing','compact');

ax = nexttile(tl);

b = bar( ...
    ax, ...
    stacked_data, ...
    'stacked', ...
    'LineWidth',0.8);

hold(ax,'on');
grid(ax,'on');
box(ax,'on');

% Same colors as original figure
b(1).FaceColor = [0.90 0.50 0.10];   % Traction
b(2).FaceColor = [0.20 0.45 0.85];   % HVAC

b(1).EdgeColor = [0.15 0.15 0.15];
b(2).EdgeColor = [0.15 0.15 0.15];

ax.FontSize = 7;
ax.LineWidth = 0.8;
ax.Color = 'w';

ax.XTick = 1:2;
ax.XTickLabel = labels;

ylabel(ax,'Energy (kWh)');

title( ...
    ax, ...
    'Seasonal Energy Comparison -- Cost Objective', ...
    'FontSize',8.5, ...
    'FontWeight','bold');

legend( ...
    ax, ...
    {'Traction','HVAC'}, ...
    'Location','northwest', ...
    'FontSize',6.5, ...
    'Box','on');

xlim(ax,[0.5 2.5]);

ymax = max(total_vals);
ylim(ax,[0 1.16*ymax]);

ax.LooseInset = max( ...
    ax.TightInset, ...
    [0.02 0.02 0.02 0.02]);

%% ------------------------------------------------
% 4. Value labels
% ------------------------------------------------

for i = 1:length(total_vals)

    % Traction value
    text( ...
        ax, ...
        i, ...
        traction_vals(i)*0.50, ...
        sprintf('%.2f',traction_vals(i)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontSize',6.5, ...
        'Color','w', ...
        'FontWeight','bold');

    % HVAC value
    text( ...
        ax, ...
        i, ...
        traction_vals(i) + hvac_vals(i)*0.50, ...
        sprintf('%.2f',hvac_vals(i)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','middle', ...
        'FontSize',6.5, ...
        'Color','w', ...
        'FontWeight','bold');

    % Total value
    text( ...
        ax, ...
        i, ...
        total_vals(i) + 0.02*ymax, ...
        sprintf('%.2f',total_vals(i)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',6.5, ...
        'Color','k');

end

%% ------------------------------------------------
% 5. Export
% ------------------------------------------------

exportgraphics( ...
    f, ...
    'fig_Seasonal_Cost_Energy.png', ...
    'Resolution',300);

disp('Saved: fig_Seasonal_Cost_Energy.png');