function output_files = seasonal_route_temperature_ieee(data_fixed, output_folder)
%% SEASONAL_ROUTE_TEMPERATURE_IEEE
% IEEE single-column publication plotting utility.
%
% Creates two figures:
%   1) Summer vs winter energy-optimal route comparison
%   2) Ambient temperature along the corresponding route arcs
%
% Both figures are designed for IEEE single-column insertion:
%   - Width: 3.5 inches
%   - Times New Roman, 6.5-8 pt fonts
%   - Vector PDF for Overleaf
%   - 600 dpi PNG backup
%
% REQUIREMENT:
%   data_fixed.coords must exist and contain N x 2 node coordinates.
%
% Usage:
%   seasonal_route_temperature_ieee
%
% or:
%   seasonal_route_temperature_ieee(data_fixed)
%
% or:
%   seasonal_route_temperature_ieee(data_fixed, 'Figures')
%
% NOTE:
%   The route definitions and route-arc temperatures below correspond to
%   the seasonal results reported in the manuscript:
%
%   Summer route : 1-2-11-14-15
%   Winter route : 1-2-6-12-15
%
%   Summer route-arc temperatures [deg C]:
%       1->2   : 31.1
%       2->11  : 28.4
%       11->14 : 28.8
%       14->15 : 28.4
%
%   Winter route-arc temperatures [deg C]:
%       1->2   : 6.3
%       2->6   : 9.1
%       6->12  : 5.5
%       12->15 : 9.7
%
% If the seasonal optimization is rerun and these values change, update
% only the route and temperature arrays in Section 3 below.

clc;

%% ========================================================================
% 1. GET INPUT DATA
% ========================================================================

if nargin < 1 || isempty(data_fixed)
    if evalin('base', 'exist(''data_fixed'',''var'')')
        data_fixed = evalin('base', 'data_fixed');
        fprintf('Using data_fixed from base workspace.\n');
    else
        error(['data_fixed was not supplied and was not found in the base ' ...
               'workspace. Run the main EV-routing model first.']);
    end
end

if ~isstruct(data_fixed) || ~isfield(data_fixed, 'coords')
    error('data_fixed.coords was not found.');
end

coords = data_fixed.coords;

if size(coords,2) ~= 2
    error('data_fixed.coords must be an N x 2 coordinate matrix.');
end

N = size(coords,1);

if N < 15
    error('At least 15 nodes are required for the reported seasonal routes.');
end

if nargin < 2 || isempty(output_folder)
    output_folder = pwd;
end

if ~exist(output_folder, 'dir')
    mkdir(output_folder);
end

%% ========================================================================
% 2. IEEE SINGLE-COLUMN STYLE
% ========================================================================

font_name = 'Times New Roman';

single_column_width_in = 3.5;

axes_font_size       = 7;
label_font_size      = 7.5;
title_font_size      = 7.5;
node_label_font_size = 6;
value_font_size      = 6.5;
legend_font_size     = 6;

line_width      = 1.15;
route_marker_sz = 4.0;
node_marker_sz  = 3.2;

%% ========================================================================
% 3. REPORTED SEASONAL ROUTES AND ROUTE-ARC TEMPERATURES
% ========================================================================

summer_route = [1 2 11 14 15];
winter_route = [1 2 6 12 15];

summer_temperature_C = [31.1 28.4 28.8 28.4];
winter_temperature_C = [6.3 9.1 5.5 9.7];

summer_arc_labels = { ...
    '1\rightarrow2', ...
    '2\rightarrow11', ...
    '11\rightarrow14', ...
    '14\rightarrow15'};

winter_arc_labels = { ...
    '1\rightarrow2', ...
    '2\rightarrow6', ...
    '6\rightarrow12', ...
    '12\rightarrow15'};

T_set = 22;
T_tol = 2;
comfort_low  = T_set - T_tol;
comfort_high = T_set + T_tol;

%% ========================================================================
% 4. COMMON NETWORK AXIS LIMITS
% ========================================================================

x_min = min(coords(:,1));
x_max = max(coords(:,1));
y_min = min(coords(:,2));
y_max = max(coords(:,2));

x_range = max(x_max - x_min, 1);
y_range = max(y_max - y_min, 1);

x_margin = 0.08 * x_range;
y_margin = 0.08 * y_range;

common_xlim = [x_min - x_margin, x_max + x_margin];
common_ylim = [y_min - y_margin, y_max + y_margin];

%% ========================================================================
% 5. FIGURE 1 — ENERGY-OPTIMAL ROUTES
% ========================================================================

fig_route = figure( ...
    'Name', 'Seasonal Energy-Optimal Routes - IEEE', ...
    'NumberTitle', 'off', ...
    'Units', 'inches', ...
    'Position', [1 1 single_column_width_in 1.85], ...
    'Color', 'w', ...
    'Renderer', 'painters');

tl_route = tiledlayout( ...
    fig_route, ...
    1, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

ax_summer_route = nexttile(tl_route, 1);

plot_route_panel( ...
    ax_summer_route, ...
    coords, ...
    summer_route, ...
    common_xlim, ...
    common_ylim, ...
    'Summer (Jul. 15, 2025)', ...
    font_name, ...
    axes_font_size, ...
    title_font_size, ...
    node_label_font_size, ...
    line_width, ...
    route_marker_sz, ...
    node_marker_sz);

ax_winter_route = nexttile(tl_route, 2);

plot_route_panel( ...
    ax_winter_route, ...
    coords, ...
    winter_route, ...
    common_xlim, ...
    common_ylim, ...
    'Winter (Jan. 15, 2025)', ...
    font_name, ...
    axes_font_size, ...
    title_font_size, ...
    node_label_font_size, ...
    line_width, ...
    route_marker_sz, ...
    node_marker_sz);

ax_winter_route.YTickLabel = [];

route_pdf = fullfile( ...
    output_folder, ...
    'fig_Seasonal_Routes_ieee.pdf');

route_png = fullfile( ...
    output_folder, ...
    'fig_Seasonal_Routes_ieee.png');

exportgraphics( ...
    fig_route, ...
    route_pdf, ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');

exportgraphics( ...
    fig_route, ...
    route_png, ...
    'Resolution', 600, ...
    'BackgroundColor', 'white');

%% ========================================================================
% 6. FIGURE 2 — AMBIENT TEMPERATURE ALONG ROUTE ARCS
% ========================================================================

fig_temp = figure( ...
    'Name', 'Seasonal Route Ambient Temperature - IEEE', ...
    'NumberTitle', 'off', ...
    'Units', 'inches', ...
    'Position', [1 1 single_column_width_in 1.95], ...
    'Color', 'w', ...
    'Renderer', 'painters');

tl_temp = tiledlayout( ...
    fig_temp, ...
    1, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

common_temp_ylim = [4 33];

ax_summer_temp = nexttile(tl_temp, 1);

plot_temperature_panel( ...
    ax_summer_temp, ...
    summer_temperature_C, ...
    summer_arc_labels, ...
    comfort_low, ...
    comfort_high, ...
    T_set, ...
    common_temp_ylim, ...
    'Summer', ...
    font_name, ...
    axes_font_size, ...
    label_font_size, ...
    title_font_size, ...
    value_font_size, ...
    line_width, ...
    false, ...
    legend_font_size);

ylabel( ...
    ax_summer_temp, ...
    'Ambient temperature (°C)', ...
    'FontName', font_name, ...
    'FontSize', label_font_size);

ax_winter_temp = nexttile(tl_temp, 2);

plot_temperature_panel( ...
    ax_winter_temp, ...
    winter_temperature_C, ...
    winter_arc_labels, ...
    comfort_low, ...
    comfort_high, ...
    T_set, ...
    common_temp_ylim, ...
    'Winter', ...
    font_name, ...
    axes_font_size, ...
    label_font_size, ...
    title_font_size, ...
    value_font_size, ...
    line_width, ...
    true, ...
    legend_font_size);

ax_winter_temp.YTickLabel = [];

temperature_pdf = fullfile( ...
    output_folder, ...
    'fig_Seasonal_Route_Temperature_Profile_ieee.pdf');

temperature_png = fullfile( ...
    output_folder, ...
    'fig_Seasonal_Route_Temperature_Profile_ieee.png');

exportgraphics( ...
    fig_temp, ...
    temperature_pdf, ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');

exportgraphics( ...
    fig_temp, ...
    temperature_png, ...
    'Resolution', 600, ...
    'BackgroundColor', 'white');

%% ========================================================================
% 7. OUTPUT STRUCTURE
% ========================================================================

output_files.route_pdf = route_pdf;
output_files.route_png = route_png;
output_files.temperature_pdf = temperature_pdf;
output_files.temperature_png = temperature_png;

fprintf('\n============================================================\n');
fprintf('IEEE SINGLE-COLUMN SEASONAL FIGURES EXPORTED\n');
fprintf('============================================================\n');
fprintf('Vector PDF files for Overleaf:\n');
fprintf('  %s\n', route_pdf);
fprintf('  %s\n', temperature_pdf);
fprintf('------------------------------------------------------------\n');
fprintf('600 dpi PNG backup files:\n');
fprintf('  %s\n', route_png);
fprintf('  %s\n', temperature_png);
fprintf('============================================================\n');

end

%% =========================================================================
% LOCAL FUNCTION — ROUTE PANEL
% =========================================================================

function plot_route_panel( ...
    ax, coords, route, x_limits, y_limits, panel_title, ...
    font_name, axes_font_size, title_font_size, node_label_font_size, ...
    line_width, route_marker_sz, node_marker_sz)

hold(ax, 'on');

plot( ...
    ax, ...
    coords(:,1), ...
    coords(:,2), ...
    'ko', ...
    'MarkerFaceColor', 'k', ...
    'MarkerSize', node_marker_sz, ...
    'HandleVisibility', 'off');

x_range = diff(x_limits);
y_range = diff(y_limits);

for node_idx = 1:size(coords,1)

    text( ...
        ax, ...
        coords(node_idx,1) + 0.012*x_range, ...
        coords(node_idx,2) + 0.018*y_range, ...
        sprintf('%d', node_idx), ...
        'FontName', font_name, ...
        'FontSize', node_label_font_size, ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', ...
        'Clipping', 'on');

end

route_xy = coords(route, :);

plot( ...
    ax, ...
    route_xy(:,1), ...
    route_xy(:,2), ...
    '-o', ...
    'LineWidth', line_width, ...
    'MarkerSize', route_marker_sz, ...
    'MarkerFaceColor', 'w', ...
    'DisplayName', 'Energy-optimal route');

xlim(ax, x_limits);
ylim(ax, y_limits);

grid(ax, 'on');
box(ax, 'on');

set( ...
    ax, ...
    'FontName', font_name, ...
    'FontSize', axes_font_size, ...
    'LineWidth', 0.7, ...
    'TickDir', 'in');

title( ...
    ax, ...
    panel_title, ...
    'FontName', font_name, ...
    'FontSize', title_font_size, ...
    'FontWeight', 'normal');

hold(ax, 'off');

end

%% =========================================================================
% LOCAL FUNCTION — TEMPERATURE PANEL
% =========================================================================

function plot_temperature_panel( ...
    ax, temperature_C, arc_labels, comfort_low, comfort_high, T_set, ...
    y_limits, panel_title, font_name, axes_font_size, label_font_size, ...
    title_font_size, value_font_size, line_width, show_legend, ...
    legend_font_size)

x = 1:numel(temperature_C);

hold(ax, 'on');

h_zone = patch( ...
    ax, ...
    [0.5 numel(x)+0.5 numel(x)+0.5 0.5], ...
    [comfort_low comfort_low comfort_high comfort_high], ...
    [0.85 0.93 0.85], ...
    'EdgeColor', 'none', ...
    'FaceAlpha', 0.55, ...
    'DisplayName', 'Comfort zone');

h_set = yline( ...
    ax, ...
    T_set, ...
    '--', ...
    'LineWidth', 0.9, ...
    'DisplayName', 'Set temperature');

h_temp = plot( ...
    ax, ...
    x, ...
    temperature_C, ...
    '-o', ...
    'LineWidth', line_width, ...
    'MarkerSize', 4.0, ...
    'MarkerFaceColor', 'w', ...
    'DisplayName', 'Ambient temperature');

for idx = 1:numel(temperature_C)

    if temperature_C(idx) >= T_set
        vertical_alignment = 'top';
        y_text = temperature_C(idx) - 0.9;
    else
        vertical_alignment = 'bottom';
        y_text = temperature_C(idx) + 0.7;
    end

    text( ...
        ax, ...
        x(idx), ...
        y_text, ...
        sprintf('%.1f°C', temperature_C(idx)), ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', vertical_alignment, ...
        'FontName', font_name, ...
        'FontSize', value_font_size);

end

xlim(ax, [0.5 numel(x)+0.5]);
ylim(ax, y_limits);

xticks(ax, x);
xticklabels(ax, arc_labels);

set( ...
    ax, ...
    'TickLabelInterpreter', 'tex', ...
    'FontName', font_name, ...
    'FontSize', axes_font_size, ...
    'LineWidth', 0.7, ...
    'TickDir', 'in');

xlabel( ...
    ax, ...
    'Energy-optimal route arc', ...
    'FontName', font_name, ...
    'FontSize', label_font_size);

title( ...
    ax, ...
    panel_title, ...
    'FontName', font_name, ...
    'FontSize', title_font_size, ...
    'FontWeight', 'normal');

grid(ax, 'on');
box(ax, 'on');

text( ...
    ax, ...
    0.62, ...
    T_set + 0.35, ...
    'Set = 22°C', ...
    'FontName', font_name, ...
    'FontSize', value_font_size, ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom');

if show_legend

    legend( ...
        ax, ...
        [h_zone h_temp h_set], ...
        {'Comfort zone', 'Ambient temp.', 'Set temp.'}, ...
        'Location', 'north', ...
        'Orientation', 'vertical', ...
        'FontName', font_name, ...
        'FontSize', legend_font_size, ...
        'Box', 'on');

end

hold(ax, 'off');

end
