%% ================================================================
% EXPORT DATA FOR PYTHON / COLAB PLOTTING
% ================================================================

labels = {'Cost Opt'; 'Time Opt'; 'Energy Opt'};

T_export = table( ...
    labels, ...
    cost_ratio(:), ...
    time_ratio(:), ...
    hvac_cost(:), ...
    hvac_time(:), ...
    total_cost(:), ...
    total_time(:), ...
    'VariableNames', { ...
        'Label', ...
        'HVAC_Cost_Ratio_Percent', ...
        'HVAC_Time_Ratio_Percent', ...
        'HVAC_Cost_USD', ...
        'HVAC_Time_Hours', ...
        'Total_Cost_USD', ...
        'Total_Time_Hours'} ...
    );

writetable(T_export, 'hvac_ratio_export.csv');
disp('Exported: hvac_ratio_export.csv');